# Generated by Django 5.2.1 on 2025-05-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_universities_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='profilePicture',
            field=models.ImageField(blank=True, db_column='profile_picture', null=True, upload_to='university-profile-pictures/'),
        ),
    ]
