# Generated by Django 5.2.1 on 2025-05-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_universities_profilepicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universities',
            old_name='profilePicture',
            new_name='profile_picture',
        ),
    ]
