# Generated by Django 5.2.1 on 2025-05-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_rename_profilepicture_universities_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universities',
            options={'managed': False},
        ),
    ]
