# Generated by Django 5.2.1 on 2025-05-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
    ]
