# Generated by Django 5.2.1 on 2025-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('university', 'University'), ('department', 'Department'), ('company', 'Company'), ('admin', 'Admin')], default='student', max_length=64),
        ),
    ]
