# Generated by Django 5.2.1 on 2025-06-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttags',
            unique_together={('post', 'tag')},
        ),
    ]
